require('base')
require('plugins')
-- require("config.ayu")
-- require("config.catppuccin")
require('config.nvimtree')
require('config.lualine')
require('config.treesitter')
require('config.gitsign')
require('config.bufferline')
require('config.coc')
require('config.telescope')
require('config.cursorline')
require("config.blamer")
